src/Entity/Ticket.php
<?php

namespace App\Entity;


use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TicketRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Ticket
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\NotNull
     * @ORM\Column(type="string", length=255,nullable=true)
     */
    private $firstName;

    /**
     * @Assert\NotNull
     * @ORM\Column(type="string", length=255,nullable=true)
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255,nullable=true)
     */
    private $country;

    /**
     * @ORM\Column(type="date",nullable=true)
     */
    private $dateBirth;

    /**
     * @ORM\Column(type="date",nullable=true)
     */
    private $dateEntry;

    /**
     * @ORM\Column(type="boolean",nullable=true)
     */
    private $fullDay;


    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\OrderTicket", inversedBy="tickets")
     * @ORM\JoinColumn(nullable=false)
     */
    private $order_ticket;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Admission", inversedBy="tickets")
     */
    private $admission;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getDateBirth(): ?\DateTimeInterface
    {
        return $this->dateBirth;
    }

    public function setDateBirth(\DateTimeInterface $dateBirth): self
    {
        $this->dateBirth = $dateBirth;

        return $this;
    }

    public function getDateEntry(): ?\DateTimeInterface
    {
        return $this->dateEntry;
    }

    public function setDateEntry(\DateTimeInterface $dateEntry): self
    {
        $this->dateEntry = $dateEntry;

        return $this;
    }

    public function getFullDay(): ?bool
    {
        return $this->fullDay;
    }

    public function setFullDay(bool $fullDay): self
    {
        $this->fullDay = $fullDay;

        return $this;
    }

    public function getFulldayLabel()
    {
        if ($this->getFullDay() == 0) {
            $label = "Demi-journée";
        } else {
            $label = "Journée";
        }
        return $label;
    }

    public function getOrderTicket(): ?orderTicket
    {
        return $this->order_ticket;
    }

    public function setOrderTicket(?orderTicket $order_ticket): self
    {
        $this->order_ticket = $order_ticket;

        return $this;
    }

    public function getAdmission(): ?Admission
    {
        return $this->admission;
    }

    public function setAdmission(?Admission $admission): self
    {
        $this->admission = $admission;

        return $this;
    }
}

src/Controller/AdvertController.php
<?php

namespace App\Controller;

use App\Entity\Ticket;
use App\Entity\OrderTicket;
use App\Form\OrderTicketType;
use App\Entity\Admission;
use App\Service\OrderManager;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\CurrencyType;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Form\Extension\Core\Type\DateIntervalType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


class AdvertController extends AbstractController
{
    private $session;

    public function __construct(SessionInterface $session)
    {
        $this->session = $session;
    }

    /**
     * @Route("/", name="home")
     */
    public function home()
    {

        $email_in_session = $this->session->get('email');

        return $this->render('advert/home.html.twig');
    }
   

    /**
     * @Route("/select", name="select")
     */
    public function select(Request $request, OrderManager $orderManager)
    {

      $defaultData = array('message' => 'myform');

      $form = $this->createFormBuilder($defaultData)
                    -> add ('dateEntry', DateType::class, 
                    ['label' => 'Date d\'entrée'
                    ]) 
                    -> add ('email', EmailType::class,)
                    -> add ('fullDay', ChoiceType::class, ['label' => 'Type','choices' => 
                        ['Journée' => true,
                        'Demi-journée' => false]
                    ])
                    -> add ('adultAdmission', IntegerType::class, ['label' => 'Nombre d\'entrées', 'attr' => array('class' => 'admissionItem', 'id' => 'admissionItem-adult',  'min' => '0', 'max' => '20')])                   
                    -> add ('seniorAdmission', IntegerType::class, ['label' => 'Nombre d\'entrées','attr' => array('class' => 'admissionItem', 'id' => 'admissionItem-senior', 'min' => '0', 'max' => '20')])
                    -> add ('childAdmission', IntegerType::class, ['label' => 'Nombre d\'entrées', 'attr' => array('class' => 'admissionItem', 'id' => 'admissionItem-child', 'min' => '0', 'max' => '20')])  
                    -> add ('lowPriceAdmission', IntegerType::class, ['label' => 'Nombre d\'entrées','attr' => array('class' => 'admissionItem', 'id' => 'admissionItem-lowPrice', 'min' => '0', 'max' => '20')])
                    -> getForm ();  

                    

      $form->handleRequest($request);
      if($form->isSubmitted() && $form->isValid()) 
    
        {
            $data = $form->getData();

            if(!$orderManager->beginOrder($data))
            {
                $this->addFlash("error","La date doit être ultérieure à aujourd'hui");
                return $this->redirectToRoute('select');
            }
            return $this->redirectToRoute('step2');
        }

        return $this->render('advert/select.html.twig', [
            'form' => $form->createView()
        ]);
        
    }
    
    /**
     * @Route("/step2", name="step2")
     */
    public function step2(Request $request, ObjectManager $manager, Session $session, 
    OrderManager $orderManager)
    
    {
        
        $em=$this->getDoctrine()->getManager();

        $order = $orderManager->createOrder();

        $form= $this->createForm(OrderTicketType::class, $order); 
        $form->handleRequest($request);
      
        if($form->isSubmitted() && $form->isValid())   
        {
            $manager->persist($order);
            $manager->flush();

            return $this->redirectToRoute('step3', array('orderId' => $order->getid()));
        } 
        
        return $this->render('advert/step2.html.twig', [
        'form' => $form->createView(), 
        ]);

    }

    /**
     * @Route("/step3/{orderId}", name="step3")
     */
    public function step3($orderId)
    {
        $orderTicket =  $this->getDoctrine()->getManager()->getRepository(OrderTicket::class)->find($orderId);

        return $this->render('advert/step3.html.twig', array('order' => $orderTicket));
    } 

    /**
     * @Route(
     *     "/charge",
     *     name="charge",
     *     methods="POST"
     * )
     */
    public function checkoutAction(Request $request, \Swift_Mailer $mailer)
    {
        \Stripe\Stripe::setApiKey("sk_test_DJhgWO9m8Fu2aXsUTVQEwnWJ00kfk8QKBu");

        // Get the credit card details submitted by the form
        $token = $request->get('stripeToken');

        // Create a charge: this will charge the user's card
        try {
            $charge = \Stripe\Charge::create(array(
                "amount" => 1000, // Amount in cents
                "currency" => "eur",
                "source" => $token,
                "description" => "Paiement Stripe - OpenClassrooms Exemple"
            ));

            $orderId=$request->get ('orderId');
            $orderTicket =$this->getDoctrine()->getManager()->getRepository(OrderTicket::class)->find($orderId);

            // send mail

                $message = (new \Swift_Message('Validation de votre commande'))
                ->setFrom('send@example.com')
                ->setTo('recipient@example.com')
                ->setBody(
                  $this->renderView(
                     'emails/confirmation.html.twig',
                      array('order' => $orderTicket) 
                  ),
                  'text/html'
                )
                ->addPart(
                    $this->renderView(
                        'emails/confirmation.txt.twig',
                         array('order' => $orderTicket)
                    ),
                    'text/plain'
                )
                ;

                $mailer->send($message);
                $this->addFlash('success','Félicitations !');
                
                return $this->render('advert/step4.html.twig',
                                array('order' => $orderTicket)
            );
            } 
        
        catch(\Stripe\Error\Card $e) {

            $this->addFlash('error','Erreur! Recommencez la transaction.');
            return $this->redirectToRoute("step3");
            // The card has been declined
        }
    }
    
    /**
     * @Route("/step4", name="step4")
     */
    public function step4()

    {
        return $this->render('advert/step4.html.twig');
    } 
      
    /**
     * @Route("/contact", name="contact")
     */
    public function contact()
    {
        return $this->render('advert/contact.html.twig');
    }  
     
    /**
     * @Route("/mentionslegales", name="mentionslegales")
     */
    public function mentionslegales()
    {
        return $this->render('advert/mentionslegales.html.twig');
    } 

}

templates/advert/contact.html.twig
{% extends 'base.html.twig' %}

{% block body %}

  <div id="wrapper"> 
          <br>
          <h3>Nous contacter</h3>
           <br> 
          <p>

            Every avid independent filmmaker has <b>Bold</b> about making that <i>Italic</i> interest documentary, 
            or short film to show off their creative prowess. 
            Many have great ideas and want to “wow” the<sup>Superscript</sup> scene, 
            or video renters with their big project.  But once you have the<sub>Subscript</sub> “in the can” 
            (no easy feat), how do you move from a <del>Strike</del> through of master DVDs with the <u>“Underline”</u> marked hand-written title inside a secondhand CD case, 
            to a pile of cardboard boxes full of shiny new, 
            retail-ready DVDs, with UPC barcodes and polywrap sitting on your doorstep?  
            You need to create eye-popping artwork and have your project replicated. 
            Using a reputable full service DVD Replication company like PacificDisc, Inc. to partner with is 
            certainly a helpful option to ensure a professional end result, but to help with your DVD replication project, here are 4 easy steps to follow for good DVD replication results: 
          </p>       


          <form method="post" action="#">
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Prénom" id="inputDefault" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Prénom'" required class="single-input">
              </div>
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Nom" id="inputDefault" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Prénom'" required class="single-input">
              </div>
              <div class="form-group">
                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"  placeholder="Adresse email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Adresse email'" required class="single-input">
                <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
              </div>        
              <div class="form-group">
                <textarea class="form-control" id="exampleTextarea" rows="3" placeholder="Message" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Message'" required></textarea>  
              </div>
              <div class="button-group-area mt-40">
                <input type="submit" value="Envoyer" class="btn btn-primary" />
              </div>
                    
          <form/>
  </div>

{% endblock %}

templates/advert/home.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <br/> <br/>
    
    <h1 class="title"> RESERVER BILLETS MUSEE DU LOUVRE</h1>

    <br/>

    <img src="img/5.jpg" alt=""/>
    <br/> <br/>

    <h3 class="title">Évitez les files d’attente au Louvre et explorez le musée à votre rythme. 
    Découvrez des expositions fascinantes et admirez des œuvres célèbres dans le monde entier comme la Joconde de Léonard de Vinci.</h3>
    <br/> <br/>
    <h2 class="title"> <a  href="{{ path ('select') }}">Billets coupe-file</a></h2>
    <br/> <br/>   <br/> <br/> 

   <h4 class="title"> MUSEE DU LOUVRE RESERVATION</h4>

    <p class="title"> <a href="{{ path ('mentionslegales') }}">Mentions légales</a></p>

{% endblock %}

templates/advert/mentionslegales.html.twig
{% extends 'base.html.twig' %}

{% block body %}
      <section class="sample-text-area">
   
          <p class="sample-text">

            <h3 class="mb-30">MENTIONS LÉGALES</h3>

            1. Présentation du site.<br>
            En vertu de l'article 6 de la loi n° 2004-575 du 21 juin 2004 pour la confiance dans l'économie numérique, il est précisé aux utilisateurs du siteBILLETS MUSEE DU LOUVRE l'identité des différents intervenants dans le cadre de sa réalisation et de son suivi : 
            Propriétaire : po po – 1 rue de propriétaire Contact du propriétaire : proprietaire@site.fr Hébergeur : hébergeur – rue des hebergeirs Contact de l'hébergeur : hebergeur@fr.fr Crédits : les mentions légales ont été générées et offertes par JBA Development développeur de sites Wordpress à Bordeaux. <br>
            <br>
            2. Conditions générales d’utilisation du site et des services proposés.<br>
            L’utilisation du site <b> BILLETS MUSEE DU LOUVRE</b> implique l’acceptation pleine et entière des conditions générales d’utilisation ci-après décrites. Ces conditions d’utilisation sont susceptibles d’être modifiées ou complétées à tout moment, les utilisateurs du siteBILLETS MUSEE DU LOUVRE sont donc invités à les consulter de manière régulière. 
            Ce site est normalement accessible à tout moment aux utilisateurs. Une interruption pour raison de maintenance technique peut être toutefois décidée par po po, qui s’efforcera alors de communiquer préalablement aux utilisateurs les dates et heures de l’intervention. 
            Le siteBILLETS MUSEE DU LOUVRE est mis à jour régulièrement par po po. De la même façon, les mentions légales peuvent être modifiées à tout moment : elles s’imposent néanmoins à l’utilisateur qui est invité à s’y référer le plus souvent possible afin d’en prendre connaissance. 
            <br><br>
            3. Limitations contractuelles sur les données techniques.<br>
            Le site utilise la technologie JavaScript.
            Le site Internet ne pourra être tenu responsable de dommages matériels liés à l’utilisation du site. De plus, l’utilisateur du site s’engage à accéder au site en utilisant un matériel récent, ne contenant pas de virus et avec un navigateur de dernière génération mis-à-jour 
            <br><br>
            4. Propriété intellectuelle et contrefaçons.<br>
            po po est propriétaire des droits de propriété intellectuelle ou détient les droits d’usage sur tous les éléments accessibles sur le site, notamment les textes, images, graphismes, logo, icônes, sons, logiciels.
            Toute reproduction, représentation, modification, publication, adaptation de tout ou partie des éléments du site, quel que soit le moyen ou le procédé utilisé, est interdite, sauf autorisation écrite préalable de : po po.
            Toute exploitation non autorisée du site ou de l’un quelconque des éléments qu’il contient sera considérée comme constitutive d’une contrefaçon et poursuivie conformément aux dispositions des articles L.335-2 et suivants du Code de Propriété Intellectuelle. 
            <br><br>
            5. Limitations de responsabilité.
            po po ne pourra être tenu responsable des dommages directs et indirects causés au matériel de l’utilisateur, lors de l’accès au siteBILLETS MUSEE DU LOUVRE, et résultant soit de l’utilisation d’un matériel ne répondant pas aux spécifications indiquées au point 4, soit de l’apparition d’un bug ou d’une incompatibilité. 
            po po ne pourra également être tenue responsable des dommages indirects (tels par exemple qu’une perte de marché ou perte d’une chance) consécutifs à l’utilisation du siteBILLETS MUSEE DU LOUVRE. Des espaces interactifs (possibilité de poser des questions dans l’espace contact) sont à la disposition des utilisateurs. po po se réserve le droit de supprimer, sans mise en demeure préalable, tout contenu déposé dans cet espace qui contreviendrait à la législation applicable en France, en particulier aux dispositions relatives à la protection des données. Le cas échéant, po po se réserve également la possibilité de mettre en cause la responsabilité civile et/ou pénale de l’utilisateur, notamment en cas de message à caractère raciste, injurieux, diffamant, ou pornographique, quel que soit le support utilisé (texte, photographie…). 
            <br><br>
            6. Gestion des données personnelles.<br>
            En France, les données personnelles sont notamment protégées par la loi n° 78-87 du 6 janvier 1978, la loi n° 2004-801 du 6 août 2004, l'article L. 226-13 du Code pénal et la Directive Européenne du 24 octobre 1995. 
            A l'occasion de l'utilisation du site <b>BILLETS MUSEE DU LOUVRE</b>, peuvent êtres recueillies : l'URL des liens par l'intermédiaire desquels l'utilisateur a accédé au siteBILLETS MUSEE DU LOUVRE, le fournisseur d'accès de l'utilisateur, l'adresse de protocole Internet (IP) de l'utilisateur. 
            En tout état de cause po po ne collecte des informations personnelles relatives à l'utilisateur que pour le besoin de certains services proposés par le site BLOG DE JEAN FORTEROCHE. L'utilisateur fournit ces informations en toute connaissance de cause, notamment lorsqu'il procède par lui-même à leur saisie. Il est alors précisé à l'utilisateur du siteBILLETS MUSEE DU LOUVRE l’obligation ou non de fournir ces informations. 
            Conformément aux dispositions des articles 38 et suivants de la loi 78-17 du 6 janvier 1978 relative à l’informatique, aux fichiers et aux libertés, tout utilisateur dispose d’un droit d’accès, de rectification et d’opposition aux données personnelles le concernant, en effectuant sa demande écrite et signée, accompagnée d’une copie du titre d’identité avec signature du titulaire de la pièce, en précisant l’adresse à laquelle la réponse doit être envoyée. 
            Aucune information personnelle de l'utilisateur du site <b>BILLETS MUSEE DU LOUVRE</b> n'est publiée à l'insu de l'utilisateur, échangée, transférée, cédée ou vendue sur un support quelconque à des tiers. Seule l'hypothèse du rachat de po po et de ses droits permettrait la transmission des dites informations à l'éventuel acquéreur qui serait à son tour tenu de la même obligation de conservation et de modification des données vis à vis de l'utilisateur du siteBILLETS MUSEE DU LOUVRE. 
            <br><br>
            7. Liens hypertextes et cookies.<br>
            Le site <b>BILLETS MUSEE DU LOUVRE </b>contient un certain nombre de liens hypertextes vers d’autres sites, mis en place avec l’autorisation de po po. Cependant, po po n’a pas la possibilité de vérifier le contenu des sites ainsi visités, et n’assumera en conséquence aucune responsabilité de ce fait. 
            La navigation sur le site <b>BILLETS MUSEE DU LOUVRE</b> est susceptible de provoquer l’installation de cookie(s) sur l’ordinateur de l’utilisateur. Un cookie est un fichier de petite taille, qui ne permet pas l’identification de l’utilisateur, mais qui enregistre des informations relatives à la navigation d’un ordinateur sur un site. Les données ainsi obtenues visent à faciliter la navigation ultérieure sur le site, et ont également vocation à permettre diverses mesures de fréquentation. 
            Le refus d’installation d’un cookie peut entraîner l’impossibilité d’accéder à certains services. L’utilisateur peut toutefois configurer son ordinateur de la manière suivante, pour refuser l’installation des cookies : 
            Sous Internet Explorer : onglet outil (pictogramme en forme de rouage en haut a droite) / options internet. Cliquez sur Confidentialité et choisissez Bloquer tous les cookies. Validez sur Ok. 
            Sous Firefox : en haut de la fenêtre du navigateur, cliquez sur le bouton Firefox, puis aller dans l'onglet Options. Cliquer sur l'onglet Vie privée. Paramétrez les Règles de conservation sur : utiliser les paramètres personnalisés pour l'historique. Enfin décochez-la pour désactiver les cookies. 
            Sous Safari : Cliquez en haut à droite du navigateur sur le pictogramme de menu (symbolisé par un rouage). Sélectionnez Paramètres. Cliquez sur Afficher les paramètres avancés. Dans la section "Confidentialité", cliquez sur Paramètres de contenu. Dans la section "Cookies", vous pouvez bloquer les cookies. 
            Sous Chrome : Cliquez en haut à droite du navigateur sur le pictogramme de menu (symbolisé par trois lignes horizontales). Sélectionnez Paramètres. Cliquez sur Afficher les paramètres avancés. Dans la section "Confidentialité", cliquez sur préférences. Dans l'onglet "Confidentialité", vous pouvez bloquer les cookies. 
            Le site est déclaré à la CNIL sous le numéro 001. 
            Les bases de données sont protégées par les dispositions de la loi du 1er juillet 1998 transposant la directive 96/9 du 11 mars 1996 relative à la protection juridique des bases de données. 
            <br><br>
            8. Droit applicable et attribution de juridiction.
            Tout litige en relation avec l’utilisation du site <b>BILLETS MUSEE DU LOUVRE</b> est soumis au droit français. Il est fait attribution exclusive de juridiction aux tribunaux compétents de Paris. 
            <br><br>
            9. Les principales lois concernées.
            Loi n° 78-17 du 6 janvier 1978, notamment modifiée par la loi n° 2004-801 du 6 août 2004 relative à l'informatique, aux fichiers et aux libertés. 
            Loi n° 2004-575 du 21 juin 2004 pour la confiance dans l'économie numérique. 
            <br><br>
            10. Lexique.
            Utilisateur : Internaute se connectant, utilisant le site susnommé. 
            Informations personnelles : « les informations qui permettent, sous quelque forme que ce soit, directement ou non, l'identification des personnes physiques auxquelles elles s'appliquent » (article 4 de la loi n° 78-17 du 6 janvier 1978).
          </p>       
     
      </section>
    {% endblock %}  

templates/advert/step2.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <br> <br> <br> <br>


    {{ form_start(form)}}

    
    {{ form_errors(form)}}

    {{ form_row(form.price) }}
    {{ form_row(form.email) }}


    <div id="allTickets">
    {{ form_row(form.tickets) }}
    </div>

    <button  type="submit" class="btn btn-primary">Sélectionner</button>
    <br><br><br>

    {{ form_end(form)}}


{% endblock %}

templates/advert/step3.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div id="wrapper">              

            <br/><h3>Cher {{ order.email }} </h3>  <br/>
            
            <h4>Rappel de votre commande:</h4>

            {% for ticket in order.tickets %}
                <hr/>
                
                Date d'entrée: {{ ticket.dateentry | date ('d/m/Y')}}<br/>
                {{ ticket.firstname }}  {{ ticket.lastname }} <br/>           
                {{ ticket.admission.AmountLabel }}  <br/>
                {{ ticket.fulldayLabel }}<br/>
                                 
                <hr/>
            {% endfor %}
          
            <h4 class="payment">Montant à régler <b> {{ order.price }} €</b></h4> 
        
            <div>
                <p>

                  <h3>  Vous êtes sur le point de payer un article qui vaut une petite fortune ! </h3>
                        <br/>
                                    
                    <script src="https://js.stripe.com/v3/"></script>

                    <form action="{{ path('charge') }}"  method="post" id="payment-form">

                    <div class="form-row">
                        <label for="card-element">
                       <h5> Carte de crédit</h5>
                        </label>
                        <div id="card-element">
                        <!-- A Stripe Element will be inserted here. -->
                        </div>

                        <!-- Used to display form errors. -->
                        <div id="card-errors" role="alert"></div>
                    </div>
                    
                    <br/>
                    <button class="btn btn-primary">Valider mon paiement</button>
                    <input type="hidden" value=" {{ order.id }}" name="orderId">
                    </form>
                </p>
            </div>
    </div>


    {% block stylesheets %}
        <style>

             #wrapper { background: #FFF; margin: 1em auto; max-width: 800px; width: 95%; }
            .form-row{ display:inline; }      
            .payment {background-color: rgb(199, 199, 230); }


        </style>
    {% endblock %}

    {% block javascripts %}
   
    <script>

        // Create a Stripe client.
        var stripe = Stripe('pk_test_JR34yEb3YAi1CfilMSdRAVTH00GVziuaPR');

        // Create an instance of Elements.
        var elements = stripe.elements();

        // Custom styling can be passed to options when creating an Element.
        // (Note that this demo uses a wider set of styles than the guide below.)
        var style = {
        base: {
            color: '#32325d',
            fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
            fontSmoothing: 'antialiased',
            fontSize: '16px',
            '::placeholder': {
            color: '#aab7c4'
            }
        },
        invalid: {
            color: '#fa755a',
            iconColor: '#fa755a'
        }
        };

        // Create an instance of the card Element.
        var card = elements.create('card', {style: style});

        // Add an instance of the card Element into the `card-element` <div>.
        card.mount('#card-element');

        // Handle real-time validation errors from the card Element.
        card.addEventListener('change', function(event) {
        var displayError = document.getElementById('card-errors');
        if (event.error) {
            displayError.textContent = event.error.message;
        } else {
            displayError.textContent = '';
        }
        });

        // Handle form submission.
        var form = document.getElementById('payment-form');
        form.addEventListener('submit', function(event) {
        event.preventDefault();

        stripe.createToken(card).then(function(result) {
            if (result.error) {
            // Inform the user if there was an error.
            var errorElement = document.getElementById('card-errors');
            errorElement.textContent = result.error.message;
            } else {
            // Send the token to your server.
            stripeTokenHandler(result.token);
            }
        });
        });

        // Submit the form with the token ID.
        function stripeTokenHandler(token) {
        // Insert the token ID into the form so it gets submitted to the server
        var form = document.getElementById('payment-form');
        var hiddenInput = document.createElement('input');
        hiddenInput.setAttribute('type', 'hidden');
        hiddenInput.setAttribute('name', 'stripeToken');
        hiddenInput.setAttribute('value', token.id);
        form.appendChild(hiddenInput);

        // Submit the form
        form.submit();
        }

    </script>

    {% endblock %}

{% endblock %}

templates/advert/step4.html.twig
{% extends 'base.html.twig' %}

{% block body %}
        <br> 
 
        {% for message in app.flashes('success') %}
            <div class="btn btn-success">
            {{ message }}
            </div>
        {% endfor %}

        {% for message in app.flashes('error') %}
            <div class="btn btn-warning">
            {{ message }}
            </div>
        {% endfor %}

            <br> <br> 
            
            <h1> MERCI POUR VOTRE ACHAT! </h1>

            <br> <br><h4 class="final"> Nous confirmons le paiement de  votre commande.<br><br>
  
            Nous venons de vous envoyer vos billets par courrier électronique.</h4>  <br> <br>
            <h5> Vérifiez votre boite mail. </h5><br> <br>
            <h3> Bonne visite! </h3>
            <br> <br>

{% endblock %}

templates/advert/translation.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    
    <h1>{% trans %}Symfony is great{% endtrans %} in english</h1>
    <h2>  {{'Hello'|trans}}  {{name}} ! in english</h2>
    <h2>  {{ 'Hello'|trans }}!  in english </h2> 
    
    <h2>  {{ 'Bienvenue'|trans }}! en français</h2>
    <h1>{% trans %}J'aime Symfony{% endtrans %}! en français</h1>

   

    <p>Lorem ipsum dolor sitconsectetur adipisicing elit. Eligendi non voluptates voluptas? </p>
    <p>Lorem ipsum dolor siciis assumenda officia quibusdam deleniti eos cupiditate dolore doloribus!</p>

{% endblock %}